version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: parking_user
      POSTGRES_PASSWORD: parking_pass
      POSTGRES_DB: parking_lot
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "3000:3000"
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://parking_user:parking_pass@db:5432/parking_lot
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db
    command: npm run dev

volumes:
  postgres_data: