# Global Serena Configuration for Parking Lot Management System

# Logging configuration
logging:
  level: "INFO"
  file_logging: true
  console_logging: true
  log_file: "serena.log"

# Dashboard settings
dashboard:
  enabled: true
  port: 24282
  auto_open: false

# Language server settings
language_servers:
  timeout: 30
  restart_on_crash: true

# Tool configuration
tools:
  shell_execution:
    enabled: true
    timeout: 30
  file_operations:
    enabled: true
    backup_on_edit: true

# Memory settings
memory:
  max_memories: 50
  auto_cleanup: true

# Project-specific settings
project_defaults:
  auto_index: true
  context_mode: "ide-assistant"
  onboarding: true

# Financial system specific reminders
custom_prompts:
  startup_reminder: |
    This is a financial parking lot management system.
    Key reminders:
    - Use Decimal.js for ALL monetary calculations
    - Spanish language for all user interfaces
    - Hardware integration with thermal printer and barcode scanner
    - Single-screen operator interface design
    - Comprehensive testing before implementation